# Generated by Django 5.0.3 on 2024-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
